### ISSUE TITLE
which python

### ISSUE THREAD

**Issue by xingpz2008** [LaRiffle/ariann#1]
Hi,

Could you please advise which version of python you were using in this repo?
Thanks in advance!

**Comment by xingpz2008** [comment]
Hi,
I also encountered the following exception
AttributeError: type object 'ScriptModule' has no attribute 'get_msgpack_code'
Any solution for this?

**Comment by LaRiffle** [comment]
Hey!
Python 3.7 or 3.8 should be good! The Docker image uses 3.7

**Comment by LaRiffle** [comment]
what command were you running when this error occured?
Can you give me the version of Pytorch you use? Also can you confirm the version of PySyft used? :)

**Comment by xingpz2008** [comment]
> what command were you running when this error occured? Can you give me the version of Pytorch you use? Also can you confirm the version of PySyft used? :)

Hi,

Thank you for your quick response.
I am using Python 3.9 and try to install from source.
I am currently using Pytorch 1.10 with cuda and PySyft mentioned in README.md

**Comment by LaRiffle** [comment]
Ah ok so with the specified version of PySyft, you should use PyTorch 1.4 (you can check the [requirements.txt](https://github.com/OpenMined/PySyft/blob/a73b13aa84a8a9ad0923d87ff1b6c8c2facdeaa6/pip-dep/requirements.txt) file associated with the pysyft version)
This should fix most of your problems. Then is not, you can change the Python version, and if it's still not working, let me know :)

**Comment by xingpz2008** [comment]
Hello again,
I have successfully run the preprocess, however, when I tried to run the private inference stage with “—test” arg, it shows that I need to install torchcsprng. The installation of torchcsprng automatically installed torch 1.8.1 and uninstalled 1.4.0 which raise the following exception when I re-try the private inference after the completion of installation.
AttributeError: type object 'ScriptModule' has no attribute 'get_msgpack_code'

I assume it is still caused due to the conflict of different version of external libs, is there anything I can do to resolve this? 
Thank you.

**Comment by LaRiffle** [comment]
Arf... You can reinstall torchcsprng at version ==0.1.2 and then manually install torch at version 1.4.0 
It should work!

**Comment by xingpz2008** [comment]
Hi,
I think the problem of incompatibility has been resolved, thank you.
Another thing to bother, does the docker of AriANN support CPU only? Can I enable CUDA acceleration in the docker version?

thank you again for your lasting help!

**Comment by LaRiffle** [comment]
Good question! I haven't tried it actually with GPUs :D

**Comment by xingpz2008** [comment]
Problem solved, issue closed.
Thanks for help.
