### ISSUE TITLE
Communication rounds data

### ISSUE THREAD

**Issue by HuangPZ** [LaRiffle/ariann#2]
Hi there! Brilliant work from your team!

One question I have when testing: the comm_info flag does not give the total communication rounds online, which to me is a major improvement of your method. Is there any way to count that? Thanks!

**Comment by LaRiffle** [comment]
Hey!
Thanks for the support and the interesting question :) 
The reason for this is that the implementation (based on some version of PySyft) is suboptimal in terms of communication rounds. Here is a very basic example: 
Say you want to compute `(x + y) + z` where all 3 tensors are secret shared. In PySyft all SMPC operations (should they use Function Secret Sharing with Ariann or not) are controlled through a MPCTensor (also sometimes called the AdditiveSharingTensor), which tells all share holders how to proceed (for addition, they should only sum their shares). So the worker holding the MPCTensor _sends_ a message to each share holder with instructions in some sense. back to our example `(x + y) + z`  it will therefore send twice the instructions to locally sum some shares. Hence, the total number of communication rounds in the implem is 2, while theoretically it would be 0, which would be the case, if the workers _had all the necessary information in advance_.
Sending this information in advance with the current PySyft paradigm would be possible with objects like `Plan` and `Protocol` that "bundle" instructions but they are as far as I know still under development.

**Comment by HuangPZ** [comment]
Thx for the explanation! Then I guess actually running is the option for now since these are still under development. 
One thing I notice from the paper is that the connection speed seems not mentioned (or maybe I'm just being dumb to miss it :p), and in the readme, I see the crossnode (WAN setting) experiment seems not to include the setup of IP addresses. I assume the experiment is done in the local simulation of PyGrid to add manual delay for each necessary round right? Is there a way to specify the latency (I assume in the code right now it's set as in the paper to be 70ms)? And for the transmission time can we just assume it to be _total package size_/_assumed speed_?
Thanks!

**Comment by LaRiffle** [comment]
> the connection speed seems not mentioned. [...] I assume the experiment is done in the local simulation of PyGrid to add manual delay for each necessary round right? Is there a way to specify the latency (I assume in the code right now it's set as in the paper to be 70ms)?

Exactly it was simulated, hence the connection speed isn't taken into account unfortunately, or put the other way around it is equal in this work to the serialization / deserialization speed + the websockets or local http bandwidth, which was our bottleneck (see https://github.com/OpenMined/PySyft/issues/4567). I assume the "effective" latency was around 90MB/s in our experiments (where we measure the time for sending one huge object).

So 90MB/s is somewhat realistic with current bandwidth on our laptops!
