### ISSUE TITLE
Amortized results in the paper

### ISSUE THREAD

**Issue by HuangPZ** [LaRiffle/ariann#4]
Hi, just to be clear that the amortized results means if say we measure the inference of a 128 batch, the final results of time and comm. are divided by 128 right?

**Comment by xingpz2008** [comment]
>  if args.comm_info:
                print(
                    "Total communication per item",
                    round(sy.comm_total / args.batch_size / 10 ** 6, 3),
                    "MB",
                )

@procedure.py, line 114

**Comment by LaRiffle** [comment]
Exactly! You count the communication _per item_ in the batch
