### ISSUE TITLE
Communication for training

### ISSUE THREAD

**Issue by khoaguin** [LaRiffle/ariann#5]
Hi,

I am trying to get the total communication overhead when training the neural networks. If I am not wrong, the `--comm_info` flag only prints out the total communication per item in the `test` function, but not for the `train` function, right?

**Comment by LaRiffle** [comment]
Hey!
You're right, it was only added in the `test` function in https://github.com/LaRiffle/ariann/blob/540e3695d9915d118b82648c26f4774a426c214e/procedure.py but it's almost a two-liner if you want to add to the `train` function to improve the lib :)

**Comment by khoaguin** [comment]
Thanks. I figured it out
