### ISSUE TITLE
no ryffel/ariaNN branch in OpenMined/PySyft？

### ISSUE THREAD

**Issue by Stu-Yang** [LaRiffle/ariann#6]
Hi, I was trying to run the code by installing from the source. but there are some errors when running the code below：
```
>>> cd ~
>>> git clone https://github.com/OpenMined/PySyft.git
>>> cd PySyft
>>> git checkout a73b13aa84a8a9ad0923d87ff1b6c8c2facdeaa6       ## some exceptions
Note: checking out 'a73b13aa84a8a9ad0923d87ff1b6c8c2facdeaa6'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at a73b13a... Remove softmax logs
>>> pip install -e .                   ## there is sone errors here
...
```
Also, I found out that there is no ryffel/ariaNN branch in OpenMined/PySyft, I think this is the crux of the problem, is that the case?

**Comment by Stu-Yang** [comment]
I think `git checkout a73b13aa84a8a9ad0923d87ff1b6c8c2facdeaa6` is no longer correct, you can try to download directly in `https://github.com/OpenMined/PySyft/tree/a73b13aa84a8a9ad0923d87ff1b6c8c2facdeaa6`

**Comment by LaRiffle** [comment]
Oh I guess my branch was deleted 😬 
I can try to re-up from a fork if it's still needed :)

**Comment by shazi4399** [comment]
> Oh I guess my branch was deleted 😬 I can try to re-up from a fork if it's still needed :)

Could you please re-upload , I think it would be convenient.

**Comment by shazi4399** [comment]
> Oh I guess my branch was deleted 😬 I can try to re-up from a fork if it's still needed :)

Could you please re-upload , I think it would be convenient.

**Comment by LaRiffle** [comment]
@shazi4399 You can use this one: [ryffel/0.2.x-fix-training](https://github.com/OpenMined/PySyft/tree/ryffel/0.2.x-fix-training)

**Comment by shazi4399** [comment]
> @shazi4399 You can use this one: [ryffel/0.2.x-fix-training](https://github.com/OpenMined/PySyft/tree/ryffel/0.2.x-fix-training)

Okay, thank you very much!

**Comment by cscy117** [comment]
Hi, @Stu-Yang 

I am currently reproducing the results of Ariann, I use this branch of syft [ryffel/0.2.x-fix-training](https://github.com/OpenMined/PySyft/tree/ryffel/0.2.x-fix-training). However, I encountered some issues while importing the torchcsprng library, torchscprng don't support torch==1.4.0, but we need torch==1.4.0 for syft==0.2.9. How to solve this problem? Thanks!

**Comment by Stu-Yang** [comment]
@SiqingZhang117 I also faced the same problem, but until now I have no solution. I noticed issue [issue#9](https://github.com/LaRiffle/ariann/issues/9) you reported, and I hope @LaRiffle can provide some help on this.

**Comment by shazi4399** [comment]
Hi !
Following the steps below, I was triyng to install PySyft version 0.2, but encountered an error during the installation. Could you please advise on how to proceed with the installation?

```shell
>>> cd ~
>>> git clone https://github.com/OpenMined/PySyft.git
>>> cd PySyft
>>> git checkout ryffel/0.2.x-fix-training
>>> pip install -e .
```
![image](https://github.com/LaRiffle/ariann/assets/25169930/70c808ad-f180-44ac-9c8c-350375eb8079)
