### ISSUE TITLE
How to view the detailed implementation of FSS ?

### ISSUE THREAD

**Issue by Stu-Yang** [LaRiffle/ariann#7]
Happy New Year, Ryffel～

Currently I am studying Function Secret Sharing(FSS) and interested in the implementation of FSS, so I would like to know how FSS is implemented in [AriaNN](https://github.com/LaRiffle/ariann).

In AriaNN, [PySyft](https://github.com/OpenMined/PySyft) is used. And then I studied the FSS implementation in PySyft, but in some branches (I used [PySyft-ryffel-0.2.x-fix-training](https://github.com/OpenMined/PySyft/tree/ryffel/0.2.x-fix-training)), FSS is implemented based on the sycret. However, the sycret in AriaNN does not give a specific implementation, the details are included in Dynamic link library (e.g. native.so) and cannot be viewed, I hope you can give some more information so that I can understand how to implement FSS.

To better describe the problem, here is an example:
```python
import torch
import torch.nn.functional as F
import syft as sy

hook = sy.TorchHook(torch)
bob = sy.VirtualWorker(hook, id="bob")
alice = sy.VirtualWorker(hook, id="alice")
crypto_provider = sy.VirtualWorker(hook, id="crypto_provider")

X = torch.rand(128, 128)
X_ = X.fix_precision(precision_fractional = 4).share(bob, alice, crypto_provider=crypto_provider, protocol="fss")

Y_ = F.relu(X_)         # call relu
Y = Y_.get()
```
In order to calculate the relu function, class `DIF` will be called, and it is defined in `PySyft/syft/frameworks/torch/mpc/fss.py`:
```python
class DIF:
    """Distributed Interval Function - used for comparison"""
    @staticmethod
    def keygen(n_values=1):
        return dif.keygen(n_values=n_values)    # dif = sycret.LeFactory(n_threads=N_CORES)

    @staticmethod
    def eval(b, x, k_b):
        # x = x.astype(np.uint64)
        original_shape = x.shape
        x = x.reshape(-1)
        flat_result = dif.eval(b, x, k_b)    # dif = sycret.LeFactory(n_threads=N_CORES)
        return flat_result.astype(np.int32).astype(np.int64).reshape(original_shape)
```
It can be seen that the `relu` function is based on the `sycret` which is located in the library of the current virtual python environment `/root/.../anconda3/envs/pysyft/lib/python3.7/site -packages/sycret`. In `sycret`, it can be seen from `from .sycret import lib` and `lib.keygen`, `lib.eval` that the specific FSS function is defined in `lib`, but `lib` cannot be viewed.

**Comment by xingpz2008** [comment]
You may refer to sycret repo for implementation details, as the author of AriANN invokes the binary library (*.so) compiled from Rust-based FSS implementation.
As to call PySyft from torch operators, they use override method to replace original operators to PySyft implemented ones.

**Comment by Stu-Yang** [comment]
@xingpz2008 Thank you for your reply~

In [sycret](https://github.com/OpenMined/sycret), there are some files (e.g. [sycret/src](https://github.com/OpenMined/sycret/tree/master/src)) that describe the details of Rust-based FSS, but in PySyft (and sycret in library), the binary library (*.so) is called. What I want to know is how to use new sycret in PySyft after modifing [sycret/src](https://github.com/OpenMined/sycret/tree/master/src) file?

**Comment by tholop** [comment]
Hi @Stu-Yang! @xingpz2008 is right, PySyft uses the Sycret Python package as a black box, thanks to the `dif` object in the snippet you cited above. Sycret is a mixed Python-Rust package: the Python wrapper calls some native code compiled from Rust and stored in this *.so file in the package installation path. 

If you modify the Rust code contained in `src`, you should recompile it and reinstall the Python package (to update the package with the new version of the binary). You can do this with [Maturin](https://www.maturin.rs/index.html) as described here: https://github.com/OpenMined/sycret#build. Let me know if you'd like more details!

**Comment by Stu-Yang** [comment]
@tholop Thank you! I'll try it now.

**Comment by Stu-Yang** [comment]
@xingpz2008 @tholop Thanks for your help, that worked.
